apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: edtech
  labels:
    part-of: edtech
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.monitoring.svc.cluster.local:4317
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc
  OTEL_LOG_LEVEL: info
  API_GATEWAY_PORT: "8080"
  USER_SERVICE_PORT: "8001"
  COURSE_SERVICE_PORT: "8002"
  CONTENT_SERVICE_PORT: "8003"
  QUIZ_SERVICE_PORT: "8004"
  NOTIFICATION_SERVICE_PORT: "8005"
  FRONTEND_PORT: "3000"
  API_GATEWAY_HOST: api-gateway.edtech.svc.cluster.local
  USER_SERVICE_HOST: user-service.edtech.svc.cluster.local
  COURSE_SERVICE_HOST: course-service.edtech.svc.cluster.local
  CONTENT_SERVICE_HOST: content-service.edtech.svc.cluster.local
  QUIZ_SERVICE_HOST: quiz-service.edtech.svc.cluster.local
  NOTIFICATION_SERVICE_HOST: notification-service.edtech.svc.cluster.local
  FRONTEND_HOST: frontend.edtech.svc.cluster.local
  POSTGRES_HOST: postgresql.edtech.svc.cluster.local
  POSTGRES_PORT: "5432"
  MYSQL_HOST: mysql.edtech.svc.cluster.local
  MYSQL_PORT: "3306"
  REDIS_HOST: redis.edtech.svc.cluster.local
  REDIS_PORT: "6379"
  USER_SERVICE_DB_NAME: user_service
  COURSE_SERVICE_DB_NAME: course_service
  CONTENT_SERVICE_DB_NAME: content_service
  QUIZ_SERVICE_DB_NAME: quiz_service
  REDIS_DB: "0"
