CREATE DATABASE IF NOT EXISTS contentdb;
CREATE DATABASE IF NOT EXISTS quizdb;
GRANT ALL PRIVILEGES ON contentdb.* TO 'edtech'@'%';
GRANT ALL PRIVILEGES ON quizdb.* TO 'edtech'@'%';
FLUSH PRIVILEGES;
