---
- name: Install Docker prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true
  tags: ["install"]

- name: Install Docker engine
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose-plugin
    state: present
  tags: ["install"]

- name: Enable Docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  tags: ["configure"]
