default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch('DB_POOL', 5) %>
  host: <%= ENV.fetch('DB_HOST', 'mysql') %>
  port: <%= ENV.fetch('DB_PORT', 3306) %>
  username: <%= ENV.fetch('DB_USER', 'edtech') %>
  password: "<%= ENV.fetch('DB_PASSWORD', 'edtech_password') %>"
  database: <%= ENV.fetch('DB_NAME', 'quizdb') %>
  ssl_mode: disabled

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
