apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: edtech
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service
  namespace: edtech
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: course-service
  namespace: edtech
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: content-service
  namespace: edtech
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quiz-service
  namespace: edtech
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: edtech
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: edtech
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter
  namespace: monitoring
