CREATE DATABASE IF NOT EXISTS contentdb;
CREATE DATABASE IF NOT EXISTS quizdb;
CREATE USER IF NOT EXISTS 'edtech'@'%' IDENTIFIED BY 'edtech';
GRANT ALL PRIVILEGES ON contentdb.* TO 'edtech'@'%';
GRANT ALL PRIVILEGES ON quizdb.* TO 'edtech'@'%';
FLUSH PRIVILEGES;
