#!/bin/bash
# install-apm-java.sh
# ====================
# Download and configure Site24x7 Java APM agent for course-service (Spring Boot).
#
# Usage: DEVICE_KEY=your_key SERVICE_NAME=edtech-course-service ./install-apm-java.sh
set -euo pipefail

DEVICE_KEY="${DEVICE_KEY:?Error: DEVICE_KEY env var must be set}"
SERVICE_NAME="${SERVICE_NAME:-edtech-course-service}"
INSTALL_DIR="${INSTALL_DIR:-/opt/site24x7}"
APM_ENDPOINT="${APM_ENDPOINT:-https://apmcollector.site24x7.com}"
LOG_LEVEL="${LOG_LEVEL:-info}"
JAR_URL="https://staticdownloads.site24x7.com/APM/Java/site24x7-java-agent.jar"

echo "======================================================"
echo " Site24x7 APM — Java (Spring Boot) Configuration"
echo " Service: ${SERVICE_NAME}"
echo "======================================================"

mkdir -p "${INSTALL_DIR}"

# Download Java APM agent JAR
echo "Downloading Site24x7 Java APM agent..."
if command -v curl &>/dev/null; then
    curl -fsSL -o "${INSTALL_DIR}/apm-agent.jar" "${JAR_URL}"
elif command -v wget &>/dev/null; then
    wget -q -O "${INSTALL_DIR}/apm-agent.jar" "${JAR_URL}"
else
    echo "ERROR: Neither curl nor wget found." >&2
    exit 1
fi

JAR_SIZE=$(du -sh "${INSTALL_DIR}/apm-agent.jar" | cut -f1)
echo "✓ Java APM agent downloaded: ${INSTALL_DIR}/apm-agent.jar (${JAR_SIZE})"

# Write environment file
cat > "${INSTALL_DIR}/java-apm.env" <<EOF
# Site24x7 Java APM Environment Variables
# Generated by install-apm-java.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
JAVA_TOOL_OPTIONS=-javaagent:${INSTALL_DIR}/apm-agent.jar
SITE24X7_APM_KEY=${DEVICE_KEY}
SITE24X7_APM_APP_NAME=${SERVICE_NAME}
SITE24X7_APM_ENDPOINT=${APM_ENDPOINT}
SITE24X7_LOG_LEVEL=${LOG_LEVEL}
EOF

chmod 640 "${INSTALL_DIR}/java-apm.env"
echo "✓ APM env file written to ${INSTALL_DIR}/java-apm.env"
echo ""
echo "Next steps:"
echo "  1. Add to the course-service systemd unit:"
echo "     EnvironmentFile=${INSTALL_DIR}/java-apm.env"
echo "  2. Run: systemctl daemon-reload && systemctl restart course-service"
echo ""
echo "No code changes are required — the agent attaches via JAVA_TOOL_OPTIONS."
