#!/bin/bash
# install-apm-python.sh
# ======================
# Install and configure Site24x7 APM for Python services (user-service/FastAPI).
#
# Usage: DEVICE_KEY=your_key SERVICE_NAME=edtech-user-service ./install-apm-python.sh
set -euo pipefail

DEVICE_KEY="${DEVICE_KEY:?Error: DEVICE_KEY env var must be set}"
SERVICE_NAME="${SERVICE_NAME:-edtech-user-service}"
INSTALL_DIR="${INSTALL_DIR:-/opt/site24x7}"
APM_ENDPOINT="${APM_ENDPOINT:-https://apmcollector.site24x7.com}"
LOG_LEVEL="${LOG_LEVEL:-info}"
PIP_CMD="${PIP_CMD:-pip3}"
VENV_PATH="${VENV_PATH:-}"   # Optional: path to Python venv

echo "======================================================"
echo " Site24x7 APM — Python (FastAPI) Configuration"
echo " Service: ${SERVICE_NAME}"
echo "======================================================"

# Determine pip command
if [[ -n "${VENV_PATH}" ]]; then
    PIP_EXEC="${VENV_PATH}/bin/pip"
    echo "Using venv: ${VENV_PATH}"
else
    PIP_EXEC="${PIP_CMD}"
fi

# Install site24x7-apm package
echo "Installing site24x7-apm Python package..."
"${PIP_EXEC}" install \
    site24x7-apm \
    opentelemetry-api \
    opentelemetry-sdk \
    opentelemetry-exporter-otlp-proto-grpc \
    opentelemetry-instrumentation-fastapi \
    opentelemetry-instrumentation-sqlalchemy \
    opentelemetry-instrumentation-httpx \
    opentelemetry-instrumentation-redis

echo "✓ site24x7-apm installed."

# Write environment file
mkdir -p "${INSTALL_DIR}"
cat > "${INSTALL_DIR}/python-apm.env" <<EOF
# Site24x7 Python APM Environment Variables
# Generated by install-apm-python.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
SITE24X7_APM_KEY=${DEVICE_KEY}
SITE24X7_SERVICE_NAME=${SERVICE_NAME}
SITE24X7_APM_ENDPOINT=${APM_ENDPOINT}
SITE24X7_LOG_LEVEL=${LOG_LEVEL}
EOF

chmod 640 "${INSTALL_DIR}/python-apm.env"
echo "✓ APM env file written to ${INSTALL_DIR}/python-apm.env"
echo ""
echo "Next steps:"
echo "  1. Add to the user-service entry point (before other imports):"
echo "     import site24x7"
echo "     site24x7.init(license_key=os.environ['SITE24X7_APM_KEY'])"
echo "  2. Add to the systemd unit: EnvironmentFile=${INSTALL_DIR}/python-apm.env"
echo "  3. Restart: systemctl daemon-reload && systemctl restart user-service"
