#!/bin/bash
# install-apm-nodejs.sh
# ======================
# Install and configure Site24x7 APM for Node.js services (content-service, frontend).
#
# Usage: DEVICE_KEY=your_key SERVICE_NAME=edtech-content-service ./install-apm-nodejs.sh
set -euo pipefail

DEVICE_KEY="${DEVICE_KEY:?Error: DEVICE_KEY env var must be set}"
SERVICE_NAME="${SERVICE_NAME:-edtech-content-service}"
INSTALL_DIR="${INSTALL_DIR:-/opt/site24x7}"
APM_ENDPOINT="${APM_ENDPOINT:-https://apmcollector.site24x7.com}"
LOG_LEVEL="${LOG_LEVEL:-info}"
NPM_CMD="${NPM_CMD:-npm}"

echo "======================================================"
echo " Site24x7 APM — Node.js Configuration"
echo " Service: ${SERVICE_NAME}"
echo "======================================================"

# Install site24x7-apm npm package
echo "Installing site24x7-apm npm package..."
"${NPM_CMD}" install -g site24x7-apm
echo "✓ site24x7-apm installed."

# Write environment file
mkdir -p "${INSTALL_DIR}"
cat > "${INSTALL_DIR}/nodejs-apm.env" <<EOF
# Site24x7 Node.js APM Environment Variables
# Generated by install-apm-nodejs.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
SITE24X7_APM_KEY=${DEVICE_KEY}
SITE24X7_SERVICE_NAME=${SERVICE_NAME}
SITE24X7_APM_ENDPOINT=${APM_ENDPOINT}
SITE24X7_LOG_LEVEL=${LOG_LEVEL}
EOF

chmod 640 "${INSTALL_DIR}/nodejs-apm.env"
echo "✓ APM env file written to ${INSTALL_DIR}/nodejs-apm.env"
echo ""
echo "Next steps:"
echo "  1. Add as the FIRST line in your entry point (src/index.ts or server.js):"
echo "     require('site24x7-apm').init({ licenseKey: process.env.SITE24X7_APM_KEY });"
echo "  2. Add to the systemd unit: EnvironmentFile=${INSTALL_DIR}/nodejs-apm.env"
echo "  3. Restart: systemctl daemon-reload && systemctl restart ${SERVICE_NAME}"
