#!/bin/bash
# install-apm-ruby.sh
# ====================
# Install and configure Site24x7 APM for Ruby services (quiz-service/Sinatra).
#
# Usage: DEVICE_KEY=your_key SERVICE_NAME=edtech-quiz-service ./install-apm-ruby.sh
set -euo pipefail

DEVICE_KEY="${DEVICE_KEY:?Error: DEVICE_KEY env var must be set}"
SERVICE_NAME="${SERVICE_NAME:-edtech-quiz-service}"
INSTALL_DIR="${INSTALL_DIR:-/opt/site24x7}"
APM_ENDPOINT="${APM_ENDPOINT:-https://apmcollector.site24x7.com}"
LOG_LEVEL="${LOG_LEVEL:-info}"
GEM_CMD="${GEM_CMD:-gem}"

echo "======================================================"
echo " Site24x7 APM — Ruby (Sinatra) Configuration"
echo " Service: ${SERVICE_NAME}"
echo "======================================================"

# Install site24x7 gem
echo "Installing site24x7 Ruby gem..."
"${GEM_CMD}" install site24x7 --no-document
echo "✓ site24x7 gem installed."

# Write environment file
mkdir -p "${INSTALL_DIR}"
cat > "${INSTALL_DIR}/ruby-apm.env" <<EOF
# Site24x7 Ruby APM Environment Variables
# Generated by install-apm-ruby.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
SITE24X7_APM_KEY=${DEVICE_KEY}
SITE24X7_SERVICE_NAME=${SERVICE_NAME}
SITE24X7_APM_ENDPOINT=${APM_ENDPOINT}
SITE24X7_LOG_LEVEL=${LOG_LEVEL}
EOF

chmod 640 "${INSTALL_DIR}/ruby-apm.env"
echo "✓ APM env file written to ${INSTALL_DIR}/ruby-apm.env"
echo ""
echo "Next steps:"
echo "  1. Add as the FIRST line in config.ru:"
echo "     require 'site24x7'"
echo "     Site24x7::APM.init(license_key: ENV['SITE24X7_APM_KEY'])"
echo "  2. Add to the systemd unit: EnvironmentFile=${INSTALL_DIR}/ruby-apm.env"
echo "  3. Restart: systemctl daemon-reload && systemctl restart quiz-service"
