#!/bin/bash
# install-apm-go.sh
# ==================
# Configure Site24x7 APM for Go services (api-gateway, notification-service).
# Go services use OpenTelemetry — no new package installation needed.
# This script writes the APM env file that the service reads at startup.
#
# Usage: DEVICE_KEY=your_key SERVICE_NAME=edtech-api-gateway ./install-apm-go.sh
set -euo pipefail

DEVICE_KEY="${DEVICE_KEY:?Error: DEVICE_KEY env var must be set}"
SERVICE_NAME="${SERVICE_NAME:-edtech-go-service}"
INSTALL_DIR="${INSTALL_DIR:-/opt/site24x7}"
APM_ENDPOINT="${APM_ENDPOINT:-https://apmcollector.site24x7.com}"
OTLP_ENDPOINT="${OTLP_ENDPOINT:-otlp.site24x7.com:4317}"
LOG_LEVEL="${LOG_LEVEL:-info}"

echo "======================================================"
echo " Site24x7 APM — Go Service Configuration"
echo " Service: ${SERVICE_NAME}"
echo "======================================================"

mkdir -p "${INSTALL_DIR}"

# Write environment file
cat > "${INSTALL_DIR}/go-apm.env" <<EOF
# Site24x7 Go APM Environment Variables
# Generated by install-apm-go.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
SITE24X7_APM_KEY=${DEVICE_KEY}
SITE24X7_SERVICE_NAME=${SERVICE_NAME}
SITE24X7_APM_ENDPOINT=${APM_ENDPOINT}
SITE24X7_OTLP_ENDPOINT=${OTLP_ENDPOINT}
SITE24X7_LOG_LEVEL=${LOG_LEVEL}
EOF

chmod 640 "${INSTALL_DIR}/go-apm.env"
echo "✓ APM env file written to ${INSTALL_DIR}/go-apm.env"
echo ""
echo "Next steps:"
echo "  1. Add to the Go service systemd unit file:"
echo "     EnvironmentFile=${INSTALL_DIR}/go-apm.env"
echo "  2. Run: systemctl daemon-reload && systemctl restart <service-name>"
echo ""
echo "No code changes are required — the existing OTel SDK"
echo "will export traces to Site24x7's OTel endpoint."
