apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: edtech
resources:
  - ../../base/edtech
patches:
  - target:
      kind: HorizontalPodAutoscaler
      name: api-gateway
    patch: |-
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: api-gateway
  - target:
      kind: HorizontalPodAutoscaler
      name: user-service
    patch: |-
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: user-service
  - target:
      kind: HorizontalPodAutoscaler
      name: course-service
    patch: |-
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: course-service
  - target:
      kind: HorizontalPodAutoscaler
      name: content-service
    patch: |-
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: content-service
  - target:
      kind: HorizontalPodAutoscaler
      name: quiz-service
    patch: |-
      $patch: delete
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: quiz-service
  - target:
      kind: Deployment
      name: api-gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: user-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: course-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: content-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: quiz-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: notification-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: StatefulSet
      name: postgresql
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: StatefulSet
      name: mysql
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
