apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: edtech
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service
  namespace: edtech
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: course-service
  namespace: edtech
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: content-service
  namespace: edtech
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quiz-service
  namespace: edtech
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: edtech
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: edtech
