otel_collector_host: "192.168.1.33"
otel_exporter_otlp_endpoint: "http://{{ otel_collector_host }}:4317"

loki_host: "192.168.1.34"
loki_push_url: "http://{{ loki_host }}:3100/loki/api/v1/push"

prometheus_host: "192.168.1.30"
jaeger_host: "192.168.1.32"

postgresql_host: "192.168.1.20"
mysql_host: "192.168.1.21"
redis_host: "192.168.1.22"

user_service_host: "192.168.1.11"
course_service_host: "192.168.1.12"
content_service_host: "192.168.1.13"
quiz_service_host: "192.168.1.14"
notification_service_host: "192.168.1.15"
api_gateway_host: "192.168.1.10"

node_exporter_version: "1.7.0"
promtail_version: "2.9.4"
prometheus_version: "2.50.1"
grafana_version: "10.4.0"
jaeger_version: "1.55.0"
otel_collector_version: "0.97.0"
loki_version: "2.9.4"
go_version: "1.22.2"
java_version: "17"
python_version: "3.11"
node_version: "20"
ruby_version: "3.2.0"

timezone: "UTC"

app_user: "edtech"
app_group: "edtech"
app_base_dir: "/opt/edtech"
repo_url: "https://github.com/vinoth-kanagaraj-14883/edtech.git"
repo_branch: "main"
log_dir: "/var/log/edtech"

prometheus_exporters:
  postgres_exporter_version: "0.15.0"
  mysqld_exporter_version: "0.15.1"
  redis_exporter_version: "1.60.0"
