apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-service
  template:
    metadata:
      labels:
        app: content-service
    spec:
      containers:
        - name: content-service
          image: ghcr.io/vinoth-kanagaraj-14883/edtech-content-service:latest
          ports:
            - containerPort: 8003
          env:
            - name: PORT
              value: "8003"
            - name: DB_HOST
              value: mysql.edtech.svc.cluster.local
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: edtech
            - name: DB_PASSWORD
              value: edtech_password
            - name: DB_NAME
              value: contentdb
          readinessProbe:
            httpGet:
              path: /ready
              port: 8003
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: content-service
spec:
  selector:
    app: content-service
  ports:
    - port: 8003
      targetPort: 8003
